<strong>CATALAGO DE DADOS DA CAMADA BRONZE</strong><br><br>
<table width="70px">
  TABELA: CLIENTE<br>	
  ORIGEM: TABELA CLIENTE EXPORTADA DO SISTEMA DESKTOP DO SALÃO PARA O FORMATO (.CSV)<br>
  EXEMPLO DO ARQUIVO: (clientes.csv)<br>
  <tr>
    <td><strong>NOME DO CAMPO</strong></td>
    <td><strong>TIPO DO DADO</strong></td>
    <td><strong>TAMANHO</strong></td>
    <td><strong>DESCRIÇÃO</strong></td>
    <td><strong>CHAVE PRIMÁRIA</strong></td>
    <td><strong>ACEITA NULO</strong></td>
  </tr>
    <td>ID_CLIENTE</td>
    <td>INT</td>
    <td align="center">7</td>
    <td>IDENTIFICADOR ÚNICO DO CLIENTE</td>
    <td align="center">S</td>
    <td align="center">N</td>
  </tr>
  <tr>
    <td>NOME</td>
    <td>Varchar</td>
    <td align="center">100</td>
    <td>INFORMA O NOME DO CLIENTE</td>
    <td align="center">N</td>
    <td align="center">N</td>
  </tr>
   <tr>
    <td>DATA_NASCIMENTO</td>
    <td>varchar</td>
    <td align="center">10</td>
    <td>INFORMA A DATA DE NASCIMENTO DO CLIENTE</td>
    <td align="center">N</td>
    <td align="center">S</td>
  </tr>
   <tr>
    <td>TELEFONE</td>
    <td>varchar</td>
    <td align="center">15</td>
    <td>INFORMA O TELEFONE CELULAR DO CLIENTE</td>
    <td align="center">N</td>
    <td align="center">S</td>
  </tr>	
</table><br><br><br>

<table width="70px">
  TABELA: PRESTADOR<br>
  ORIGEM: TABELA PRESTADOR EXPORTADA DO SISTEMA DESKTOP DO SALÃO PARA O FORMATO (.CSV)<br>
  EXEMPLO DO ARQUIVO: (prestador.csv)<br>
  </tr>
  <tr>
    <td><strong>NOME DO CAMPO</strong></td>
    <td><strong>TIPO DO DADO</strong></td>
    <td><strong>TAMANHO</strong></td>
    <td><strong>DESCRIÇÃO</strong></td>
    <td><strong>CHAVE PRIMÁRIA</strong></td>
    <td><strong>ACEITA NULO</strong></td>
  </tr>
    <td>ID PRESTADOR</td>
    <td>INT</td>
    <td align="center">7</td>
    <td>IDENTIFICADOR ÚNICO DO PRESTADOR</td>
    <td align="center">S</td>
    <td align="center">N</td>
  </tr>
  <tr>
    <td>APELIDO</td>
    <td>Varchar</td>
    <td align="center">50</td>
    <td>INFORMA O APELIDO DO PROFISSIONAL</td>
    <td align="center">N</td>
    <td align="center">N</td>
  </tr>
   <tr>
    <td>NOME</td>
    <td>varchar</td>
    <td align="center">100</td>
    <td>INFORMA O NOME DO PROFISSIONAL</td>
    <td align="center">N</td>
    <td align="center">N</td>
  </tr>
   <tr>
    <td>DATA_NASCIMENTO</td>
    <td>varchar</td>
    <td align="center">15</td>
    <td>INFORMA A DATA NASCIMENTO DO PROFISSIONAL</td>
    <td align="center">N</td>
    <td align="center">S</td>
  </tr>	
  <tr>
    <td>FUNCAO</td>
    <td>varchar</td>
    <td align="center">50</td>
    <td>INFORMA A FUNÇÃO EXERCIDA PELO PROFISSIONAL</td>
    <td align="center">N</td>
    <td align="center">N</td>
  </tr>	
  <tr>
    <td>PIX</td>
    <td>varchar</td>
    <td align="center">50</td>
    <td>INFORMA O NÚMERO DO PIX DO PROFISSIONAL</td>
    <td align="center">N</td>
    <td align="center">S</td>
  </tr>	
  <tr>
    <td>ATIVO</td>
    <td>varchar</td>
    <td align="center">1</td>
    <td>INFORMA SE O PROSSIONAL CONTINUA TRABALHANDO NA EMPRESA. ACEITA('S' OU 'N')</td>
    <td align="center">N</td>
    <td align="center">N</td>
  </tr>		
</table><br><br>

<table width="70px">
  TABELA: PAGAMENTOS<br>
  ORIGEM: TABELA PAGAMENTOS EXPORTADA DO SISTEMA DESKTOP DO SALÃO PARA O FORMATO (.CSV)<br>
  EXEMPLO DO ARQUIVO: (pagamentos.csv)<br>

  <tr>
    <td><strong>NOME DO CAMPO</strong></td>
    <td><strong>TIPO DO DADO</strong></td>
    <td><strong>TAMANHO</strong></td>
    <td><strong>DESCRIÇÃO</strong></td>
    <td><strong>CHAVE PRIMÁRIA</strong></td>
    <td><strong>CHAVE ESTRANGEIRA</strong></td>	  
    <td><strong>ACEITA NULO</strong></td>
  </tr>
    <td>ID_PAGAMENTO</td>
    <td>INT</td>
    <td align="center">7</td>
    <td>IDENTIFICADOR ÚNICO DO PAGAMENTO</td>
    <td align="center">S</td>
    <td></td>	
    <td align="center">N</td>
  </tr>
  <tr>
    <td>ID_COMANDA</td>
    <td>INT</td>
    <td align="center">50</td>
    <td>NÚMERO DE COMANDA GERADA NO ATENDIMENTO DO CLIENTE</td>
    <td align="center">N</td>
    <td>(SIM) JUNÇÃO C\ A TABELA COMANDA</td>		  
    <td align="center">N</td>
  </tr>
   <tr>
    <td>VALOR_PAGTO</td>
    <td>decimal</td>
    <td align="center">(10,2)</td>
    <td>INFORMA O VALOR PAGO PELO CLIENTE PELO SERVIÇOS FEITOS</td>
    <td align="center">N</td>
    <td></td>	
    <td align="center">N</td>
  </tr>
   <tr>
    <td>FORMA_PAGO</td>
    <td>varchar</td>
    <td align="center">50</td>
    <td>INFORMA A FORMA DE PAGAMENTO QUE O CLIENTE EFETUOU.ACEITANDO (DINHEIRO, PIX, DÉBITO E CRÉDITO)</td>
    <td align="center">N</td>
    <td></td>	
    <td align="center">N</td>
  </tr>	
  <tr>
    <td alingn="left">DATA_PAGAMENTO</td>
    <td>DATETIME</td>
    <td align="center">10</td>
    <td>INFORMA A DATA A QUE O CLIENTE EFETUOU O PAGAMENTO</td>
    <td align="center">N</td>
    <td></td>	
    <td align="center">N</td>
  </tr>	 
</table><br><br>
<table width="70px">
  TABELA: SERVICOS<br>
  ORIGEM: TABELA SERVICOS EXPORTADA DO SISTEMA DESKTOP DO SALÃO PARA O FORMATO (.CSV)<br>
  EXEMPLO DO ARQUIVO: (servicos.csv)<br>
  <tr>
    <td><strong>NOME DO CAMPO</strong></td>
    <td><strong>TIPO DO DADO</strong></td>
    <td><strong>TAMANHO</strong></td>
    <td><strong>DESCRIÇÃO</strong></td>
    <td><strong>CHAVE PRIMÁRIA</strong></td>
    <td><strong>ACEITA NULO</strong></td>
  </tr>
    <td>ID_SERVICO</td>
    <td>INT</td>
    <td align="center">7</td>
    <td>IDENTIFICADOR ÚNICO DO SERVIÇO</td>
    <td align="center">S</td>
    <td align="center">N</td>
  </tr>
  <tr>
    <td>DESCRIÇÃO</td>
    <td>Varchar</td>
    <td align="center">100</td>
    <td>INFORMA A DESCRIÇÃO DOS SERVIÇOS OFERECIDOS PELO SALÃO</td>
    <td align="center">N</td>
    <td align="center">N</td>
  </tr>
   <tr>
    <td>FUNCAO</td>
    <td>varchar</td>
    <td align="center">100</td>
    <td>INFORMA A FUNÇÃO DO PRESTADAOR E CARREGA OS SERVIÇOS QUE ESTÁ LIGADO A SUA FUNÇÃO</td>
    <td align="center">N</td>
    <td align="center">N</td>
  </tr>
   <tr>
    <td>VALOR</td>
    <td>DECIMAL</td>
    <td align="center">(10,2)</td>
    <td>INFORMA O VALOR DO SERVIÇOS</td>
    <td align="center">N</td>
    <td align="center">N</td>
  </tr>	
<tr>
    <td>COMISSAO</td>
    <td>INT</td>
    <td align="center">7</td>
    <td>INFORMA A COMISSÃO A SER PAGA PELO SERVIÇO FEITO PRESTADOR</td>
    <td align="center">N</td>
    <td align="center">N</td>
  </tr>	
</table><br><br>
<table width="70px">
  TABELA: COMANDACLIENTE<br>
  ORIGEM: TABELA COMANDACLIENTE EXPORTADA DO SISTEMA DESKTOP DO SALÃO PARA O FORMATO (.CSV)<br>
  EXEMPLO DO ARQUIVO: (comandacliente.csv)<br>
  <tr>
    <td><strong>NOME DO CAMPO</strong></td>
    <td><strong>TIPO DO DADO</strong></td>
    <td><strong>TAMANHO</strong></td>
    <td><strong>DESCRIÇÃO</strong></td>
    <td><strong>CHAVE PRIMÁRIA</strong></td>
    <td><strong>CHAVE ESTRANGEIRA</strong></td>	  
    <td><strong>ACEITA NULO</strong></td>
  </tr>
    <td>ID</td>
    <td>INT</td>
    <td align="center">7</td>
    <td>IDENTIFICADOR ÚNICO DA COMANDACLIENTE</td>
    <td align="center">S</td>
    <td></td>	
    <td align="center">N</td>
  </tr>
  <tr>
    <td>DATA_SERVICO</td>
    <td>DATE</td>
    <td align="center">10</td>
    <td>INFORMA A DATA QUE O CLIENTE FEZ O SERVIÇO NO SALÃO</td>
    <td align="center">N</td>
    <td></td>		  
    <td align="center">N</td>
	
  </tr>
   <tr>
    <td>ID_COMANDA</td>
    <td>INT</td>
    <td align="center">7</td>
    <td>NÚMERO DE COMANDA GERADA NO ATENDIMENTO DO CLIENTE</td>
    <td align="center">N</td>
    <td>(SIM) JUNÇÃO COM A TABELA COMANDA</td>	
    <td align="center">N</td>
  </tr>
   <tr>
    <td>ID_PRESTADOR</td>
    <td>INT</td>
    <td align="center">7</td>
    <td>INFORMA O PRESTADOR QUE FEZ O SERVIÇO NO CLIENTE</td>
    <td align="center">N</td>
    <td>(SIM) JUNÇÃO COM A TABELA PRESTADOR</td>	
    <td align="center">N</td>
  </tr>	
  <tr>
     <td>ID_SERVICO</td>
    <td>INT</td>
    <td align="center">7</td>
    <td>INFORMA O SERVIÇO QUE FOI FEITO PELO CLIENTE</td>
    <td align="center">N</td>
    <td>(SIM) JUNÇÃO COM A TABELA SERVICO</td>	
    <td align="center">N</td>
  </tr>	 
<tr>
     <td>ID_CLIENTE</td>
    <td>INT</td>
    <td align="center">7</td>
    <td>INFORMA O CLIENTE</td>
    <td align="center">N</td>
    <td>(SIM) JUNÇÃO COM A TABELA CLIENTE</td>	
    <td align="center">N</td>
  </tr>	 

<tr>
     <td>VALOR</td>
    <td>DECIMAL</td>
    <td align="center">(10,2)</td>
    <td>INFORMA O VALOR DO SERVIÇO FEITO PELO CLIENTE</td>
    <td align="center">N</td>
    <td></td>	
    <td align="center">N</td>
  </tr>
<tr>
     <td>COMISSAO</td>
    <td>INT</td>
    <td align="center">7</td>
    <td>INFORMA A COMISSÃO A SER PAGA PARA O PRESTADOR PELO SERVIÇO FEITO</td>
    <td align="center">N</td>
    <td></td>	
    <td align="center">N</td>
  </tr>	 	 
</table><br><br>

<strong>CATALAGO DE DADOS DA CAMADA PRATA</strong><br><br>
<table>
  TABELA: CLIENTES<br>
  ORIGEM: TABELA CLIENTES DO DATABASE BRONZE JÁ TRATADA<br>
  EXEMPLO DO ARQUIVO: (Clientes.sql)<br>  
  <tr>
    <td><strong>NOME DO CAMPO</strong></td>
    <td><strong>TIPO DO DADO</strong></td>
    <td><strong>TAMANHO</strong></td>
    <td><strong>DESCRIÇÃO</strong></td>
    <td><strong>CHAVE PRIMÁRIA</strong></td>
    <td><strong>ACEITA NULO</strong></td>
  </tr>
    <td>ID_CLIENTE</td>
    <td>INT</td>
    <td align="center">7</td>
    <td>IDENTIFICADOR ÚNICO DO CLIENTE</td>
    <td align="center">S</td>
    <td align="center">N</td>
  </tr>
  <tr>
    <td>NOME</td>
    <td>Varchar</td>
    <td align="center">100</td>
    <td>INFORMA O NOME DO CLIENTE</td>
    <td align="center">N</td>
    <td align="center">N</td>  
</table><br><br>
<table>
  TABELA: PRESTADOR<br>
  ORIGEM: TABELA PRESTADOR DO DATABASE BRONZE JÁ TRATADA<br>
  EXEMPLO DO ARQUIVO: (prestador.sql)<br>  
  <tr>
    <td><strong>NOME DO CAMPO</strong></td>
    <td><strong>TIPO DO DADO</strong></td>
    <td><strong>TAMANHO</strong></td>
    <td><strong>DESCRIÇÃO</strong></td>
    <td><strong>CHAVE PRIMÁRIA</strong></td>
    <td><strong>ACEITA NULO</strong></td>
  </tr>
    <td>ID PRESTADOR</td>
    <td>INT</td>
    <td align="center">7</td>
    <td>IDENTIFICADOR ÚNICO DO PRESTADOR</td>
    <td align="center">S</td>
    <td align="center">N</td>
  </tr>
  <tr>
    <td>APELIDO</td>
    <td>Varchar</td>
    <td align="center">50</td>
    <td>INFORMA O APELIDO DO PROFISSIONAL</td>
    <td align="center">N</td>
    <td align="center">N</td>
  </tr>
   <tr>
    <td>NOME</td>
    <td>varchar</td>
    <td align="center">100</td>
    <td>INFORMA O NOME DO PROFISSIONAL</td>
    <td align="center">N</td>
    <td align="center">N</td>
  </tr> 
  <tr>
    <td>FUNCAO</td>
    <td>varchar</td>
    <td align="center">50</td>
    <td>INFORMA A FUNÇÃO EXERCIDA PELO PROFISSIONAL</td>
    <td align="center">N</td>
    <td align="center">N</td>
  </tr>	
  <tr>
    <td>PIX</td>
    <td>varchar</td>
    <td align="center">50</td>
    <td>INFORMA O NÚMERO DO PIX DO PROFISSIONAL</td>
    <td align="center">N</td>
    <td align="center">S</td>
  </tr>	
  <tr>
    <td>ATIVO</td>
    <td>varchar</td>
    <td align="center">1</td>
    <td>INFORMA SE O PROSSIONAL CONTINUA TRABALHANDO NA EMPRESA. ACEITA('S' OU 'N')</td>
    <td align="center">N</td>
    <td align="center">N</td>
  </tr>		
</table><br><br>
<table>
   TABELA: COMANDACLIENTE<br>
   ORIGEM: TABELA COMANDACLIENTE DO DATABASE BRONZE JÁ TRATADA<br>  
   EXEMPLO DO ARQUIVO: (comandacliente.sql)<br>
  <tr>
    <td><strong>NOME DO CAMPO</strong></td>
    <td><strong>TIPO DO DADO</strong></td>
    <td><strong>TAMANHO</strong></td>
    <td><strong>DESCRIÇÃO</strong></td>
    <td><strong>CHAVE PRIMÁRIA</strong></td>
    <td><strong>CHAVE ESTRANGEIRA</strong></td>	  
    <td><strong>ACEITA NULO</strong></td>
  </tr>
    <td>ID</td>
    <td>INT</td>
    <td align="center">7</td>
    <td>IDENTIFICADOR ÚNICO DA COMANDACLIENTE</td>
    <td align="center">S</td>
    <td></td>	
    <td align="center">N</td>
  </tr>
  <tr>
    <td>DATA_SERVICO</td>
    <td>DATE</td>
    <td align="center">10</td>
    <td>INFORMA A DATA QUE O CLIENTE FEZ O SERVIÇO NO SALÃO</td>
    <td align="center">N</td>
    <td></td>		  
    <td align="center">N</td>
	
  </tr>
   <tr>
    <td>ID_COMANDA</td>
    <td>INT</td>
    <td align="center">7</td>
    <td>NÚMERO DE COMANDA GERADA NO ATENDIMENTO DO CLIENTE</td>
    <td align="center">N</td>
    <td>(SIM) JUNÇÃO COM A TABELA COMANDA</td>	
    <td align="center">N</td>
  </tr>
   <tr>
    <td>ID_PRESTADOR</td>
    <td>INT</td>
    <td align="center">7</td>
    <td>INFORMA O PRESTADOR QUE FEZ O SERVIÇO NO CLIENTE</td>
    <td align="center">N</td>
    <td>(SIM) JUNÇÃO COM A TABELA PRESTADOR</td>	
    <td align="center">N</td>
  </tr>	
  <tr>
     <td>ID_SERVICO</td>
    <td>INT</td>
    <td align="center">7</td>
    <td>INFORMA O SERVIÇO QUE FOI FEITO PELO CLIENTE</td>
    <td align="center">N</td>
    <td>(SIM) JUNÇÃO COM A TABELA SERVICO</td>	
    <td align="center">N</td>
  </tr>	 
<tr>
     <td>ID_CLIENTE</td>
    <td>INT</td>
    <td align="center">7</td>
    <td>INFORMA O CLIENTE</td>
    <td align="center">N</td>
    <td>(SIM) JUNÇÃO COM A TABELA CLIENTE</td>	
    <td align="center">N</td>
  </tr>	 

<tr>
     <td>VALOR</td>
    <td>DECIMAL</td>
    <td align="center">(10,2)</td>
    <td>INFORMA O VALOR DO SERVIÇO FEITO PELO CLIENTE</td>
    <td align="center">N</td>
    <td></td>	
    <td align="center">N</td>
  </tr>
<tr>
     <td>COMISSAO</td>
    <td>INT</td>
    <td align="center">7</td>
    <td>INFORMA A COMISSÃO A SER PAGA PARA O PRESTADOR PELO SERVIÇO FEITO</td>
    <td align="center">N</td>
    <td></td>	
    <td align="center">N</td>
  </tr>	 
<tr>
     <td>ANO</td>
    <td>INT</td>
    <td align="center">7</td>
    <td>INFORMA O ANO DO DA DATA DO SERVIÇO - CRIADO PARA FACILITAR A RESPOSTA DO QUESITO</td>
    <td align="center">N</td>
    <td></td>	
    <td align="center">N</td>
  </tr>	 
<tr>
     <td>MES</td>
    <td>INT</td>
    <td align="center">7</td>
    <td>IINFORMA O MÊS DA DATA DO  SERVIÇO - CRIADO PARA FACILITAR A RESPOSTA DO QUESITO</td>
    <td align="center">N</td>
    <td></td>	
    <td align="center">N</td>
  </tr>	 			 
</table><br><br>

<strong>CATALAGO DE DADOS DA CAMADA OURO</strong><br><br>
<table>
  TABELA: TABELA PAGAMENTOS<br>
  ORIGEM: CONSULTA SQL NO DATABASE PRATA PARA TRANSFORMAR EM UMA TABELA<br>
  EXEMPLO DO ARQUIVO: (pagamentos.sql)<br>  
  <tr>
    <td><strong>NOME DO CAMPO</strong></td>
    <td><strong>TIPO DO DADO</strong></td>
    <td><strong>TAMANHO</strong></td>
    <td><strong>DESCRIÇÃO</strong></td>
    <td><strong>CHAVE PRIMÁRIA</strong></td>
    <td><strong>ACEITA NULO</strong></td>
  </tr>
    <td>ANO</td>
    <td>INT</td>
    <td align="center">7</td>
    <td>ANO DA DATA DE PAGAMENTO</td>
    <td align="center">N</td>
    <td align="center">N</td>
  </tr>
  <tr>
    <td>MES</td>
    <td>Varchar</td>
    <td align="center">50</td>
    <td>MÊS DA DATA DE PAGAMENTO</td>
    <td align="center">N</td>
    <td align="center">N</td>  
   </tr>	
   <tr>
    <td>VALOR_PAGO</td>
    <td>Decimal</td>
    <td align="center">(10,2)</td>
    <td>INFORMA VALOR PAGO PELO CLIENTE</td>
    <td align="center">N</td>
    <td align="center">N</td>  
   </tr>
   <tr>
    <td>FORMA_PAGTO</td>
    <td>varchar</td>
    <td align="center">15</td>
    <td>INFORMA A FORMA DE PAGAMENTO FEITO PELO CLIENTE</td>
    <td align="center">N</td>
    <td align="center">N</td>  
   </tr>	
</table><br><br>
<table>
   TABELA: COMANDACLIENTE<br>
   ORIGEM: CONSULTA SQL NO DATABASE PRATA PARA TRANSFORMAR EM UMA TABELA<br>  
   EXEMPLO DO ARQUIVO: (comandacliente.sql)<br>
  <tr>
    <td><strong>NOME DO CAMPO</strong></td>
    <td><strong>TIPO DO DADO</strong></td>
    <td><strong>TAMANHO</strong></td>
    <td><strong>DESCRIÇÃO</strong></td>
    <td><strong>CHAVE PRIMÁRIA</strong></td>    
    <td><strong>ACEITA NULO</strong></td>
  </tr>
    <td>ANO_SERVICO</td>
    <td>INT</td>
    <td align="center">7</td>
    <td>INFORMA ANO DO SERVIÇO FEITO PELO PRESTADOR</td>
    <td align="center">N</td>   
    <td align="center">N</td>
  </tr>
  <tr>
    <td>NOME_PRESTADOR</td>
    <td>Varchar</td>
    <td align="center">100</td>
    <td>INFORMA O NOME DO PRESTADOR</td>
    <td align="center">N</td>   	  
    <td align="center">N</td>	
  </tr>
   <tr>
    <td>VALOR_SERVICO</td>
    <td>decimal</td>
    <td align="center">(10,2)</td>
    <td>INFORMA A DESCRIÇÃO DO SERVIÇO </td>
    <td align="center">N</td>   
    <td align="center">N</td>
  </tr>
   <tr>
    <td>COMISSAO_SERVICO</td>
    <td>INT</td>
    <td align="center">7</td>
    <td>INFORMA  A PORCENTAGEM QUE O PRESTADOR VAI GANHAR PELO SERVIÇO FEITO</td>
    <td align="center">N</td>   
    <td align="center">N</td>
  </tr>
<tr>
    <td>DESCRICAO</td>
    <td>VARCHAR</td>
    <td align="center">100</td>
    <td>INFORMA A DESCRIÇÃO DO SERVIÇO </td>
    <td align="center">N</td>   
    <td align="center">N</td>
  </tr>
   <tr>
    <td>MES</td>
    <td>varchar</td>
    <td align="center">15</td>
    <td>INFORMA MÊS DO SERVIÇO FEITO PELO PRESTADOR</td>
    <td align="center">N</td>    
    <td align="center">N</td>
  </tr>	  		 
</table><br><br>
<table>
   TABELA: GASTO_CLIENTE<br>
   ORIGEM: CONSULTA SQL NO DATABASE PRATA PARA TRANSFORMAR EM UMA TABELA<br>  
   EXEMPLO DO ARQUIVO: (gasto_cliente.sql)<br>
  <tr>
    <td><strong>NOME DO CAMPO</strong></td>
    <td><strong>TIPO DO DADO</strong></td>
    <td><strong>TAMANHO</strong></td>
    <td><strong>DESCRIÇÃO</strong></td>
    <td><strong>CHAVE PRIMÁRIA</strong></td>    
    <td><strong>ACEITA NULO</strong></td>
  </tr>
    <td>ANO</td>
    <td>INT</td>
    <td align="center">7</td>
    <td>INFORMA ANO PAGAMENTO FEITO PELO CLIENTE</td>
    <td align="center">N</td>   
    <td align="center">N</td>
  </tr>
  <tr>
    <td>NOMECLIENTE</td>
    <td>Varchar</td>
    <td align="center">100</td>
    <td>INFORMA NOME DO CLIENTE</td>
    <td align="center">N</td>   	  
    <td align="center">N</td>	
  </tr>
   <tr>
    <td>VL_GASTO_CLIENTE</td>
    <td>decimal</td>
    <td align="center">(10,2)</td>
    <td>INFORMA O VALOR  GASTO ANUALMENTE PELO CLIENTE</td>
    <td align="center">N</td>   
    <td align="center">N</td> 	 
</tr>
</table><br><br>
<table>
   TABELA: GASTOMENSAL<br>
   ORIGEM: CONSULTA SQL NO DATABASE PRATA PARA TRANSFORMAR EM UMA TABELA<br>  
   EXEMPLO DO ARQUIVO: (GASTOMENSAL.sql)<br>
  <tr>
    <td><strong>NOME DO CAMPO</strong></td>
    <td><strong>TIPO DO DADO</strong></td>
    <td><strong>TAMANHO</strong></td>
    <td><strong>DESCRIÇÃO</strong></td>
    <td><strong>CHAVE PRIMÁRIA</strong></td>    
    <td><strong>ACEITA NULO</strong></td>
  </tr>
    <td>ANO</td>
    <td>INT</td>
    <td align="center">7</td>
    <td>INFORMA ANO SERVIÇO FEITO PELO CLIENTE</td>
    <td align="center">N</td>   
    <td align="center">N</td>
  </tr>
  <tr>
    <td>INFORMA MÊS SERVIÇO FEITO PELO CLIENTE</td>
    <td>Varchar</td>
    <td align="center">100</td>
    <td>INFORMA NOME DO CLIENTE</td>
    <td align="center">N</td>   	  
    <td align="center">N</td>	
  </tr>
   <tr>
    <td>VL_GASTO_CLIENTE</td>
    <td>decimal</td>
    <td align="center">(10,2)</td>
    <td>INFORMA O VALOR  GASTO MENSALMENTE</td>
    <td align="center">N</td>   
    <td align="center">N</td> 	 
</tr>
</table><br><br>
<table>
   TABELA: FATURAMENTOMENSAL<br>
   ORIGEM: CONSULTA SQL NO DATABASE PRATA PARA TRANSFORMAR EM UMA TABELA<br>  
   EXEMPLO DO ARQUIVO: (FATURAMENTOMENSAL.sql)<br>
  <tr>
    <td><strong>NOME DO CAMPO</strong></td>
    <td><strong>TIPO DO DADO</strong></td>
    <td><strong>TAMANHO</strong></td>
    <td><strong>DESCRIÇÃO</strong></td>
    <td><strong>CHAVE PRIMÁRIA</strong></td>    
    <td><strong>ACEITA NULO</strong></td>
  </tr>
    <td>ANO</td>
    <td>INT</td>
    <td align="center">7</td>
    <td>INFORMA ANO PAGAMENTO FEITO PELO CLIENTE</td>
    <td align="center">N</td>   
    <td align="center">N</td>
  </tr>
  <tr>    	
    <td>MES</td>
    <td>Varchar</td>
    <td align="center">15</td>
    <td>INFORMA MÊS DO PAGAMENTO FEITO PELO CLIENTE</td>
    <td align="center">N</td>   	  
    <td align="center">N</td>	
  </tr>
   <tr>
    <td>VL_FATURAMENTO_MENSAL</td>
    <td>decimal</td>
    <td align="center">(10,2)</td>
    <td>INFORMA O VALOR DO FATURAMENTO MENSAL</td>
    <td align="center">N</td>   
    <td align="center">N</td> 	 
</tr>
</table><br><br>